### ISSUE TITLE
TextMode.PRESERVE still not working as it did in JDOM 1 -- now instead of always inserting new lines, it NEVER inserts new lines

### ISSUE THREAD

**Issue by Vanilla5113** [hunterhacker/jdom#167] opened 2017-10-06 19:48 UTC
Using the following code:
```
Format format = Format.getRawFormat();
format.setIndent("\t");
format.setLineSeparator("\r\n");
format.setTextMode(Format.TextMode.PRESERVE);

strResponse = new XMLOutputter(format).outputString(document);
```
With JDOM 1.1.3, this gives me an output string with new lines. When I tried it with 2.0.5, I got new lines even between the opening and closing tags and the text value. I see the change made for this in the FormatStack class:
```
mode[depth] = format.getTextMode();
if (mode[depth] == TextMode.PRESERVE) {
    // undo any special indenting and end-of-line management:
    levelIndent[depth] = null;
    levelEOL[depth] = null;
    levelEOLIndent[depth] = null;
    termEOLIndent[depth] = null;
} else {
    levelIndent[depth] = format.getIndent() == null
            ? null : "";
    levelEOL[depth] = format.getLineSeparator();
    levelEOLIndent[depth] = levelIndent[depth] == null ?  
            null : levelEOL[depth];
    termEOLIndent[depth] = levelEOLIndent[depth];

}
```
..but I'm not sure it's what was intended. For TextMode.PRESERVE, it sets them all to null, but these are used by these methods:
```
/**
 * Get the end-of-line indenting sequence for before the first item in an
 * Element, as well as between subsequent items (but not after the last item)
 * @return the String EOL sequence followed by an indent. Null if it should 
 * be ignored
 */
public String getPadBetween() {
	return levelEOLIndent[depth];
}

/**
 * Get the end-of-line indenting sequence for after the last item in an
 * Element
 * @return the String EOL sequence followed by an indent. Null if it should 
 * be ignored
 */
public String getPadLast() {
	return termEOLIndent[depth];
}
```
..which are used when printing the content. (more about that below)

With 2.0.6, I only get a new line after the xml declaration, but then the response body is all one line. This apparently has to do with the FormatStack class. In the printDeclaration method of AbstractXMLOutputProcessor, on line 595 it uses fstack.getLineSeparator() to print the new line afterwards: `write(out, fstack.getLineSeparator());`

However, in the printElement method (code segment below starts on line 845):
```
// note we ensure the FStack is right before creating the walker
Walker walker = buildWalker(fstack, content, true);

if (!walker.hasNext()) {
	// the walker has formatted out whatever content we had
	if (fstack.isExpandEmptyElements()) {
		write(out, "></");
		write(out, element.getQualifiedName());
		write(out, ">");
	}
	else {
		write(out, " />");
	}
	// nothing more to do.
	return;
}
// we have some content.
write(out, ">");
if (!walker.isAllText()) {
	// we need to newline/indent
	textRaw(out, fstack.getPadBetween());
}

printContent(out, fstack, nstack, walker);

if (!walker.isAllText()) {
	// we need to newline/indent
	textRaw(out, fstack.getPadLast());
}
write(out, "</");
write(out, element.getQualifiedName());
write(out, ">");
```
..it uses fstack.getPadBetween() and fstack.getPadLast() before and after printing the content. But, as mentioned earlier, these both return nulls in this case, so no new lines are written.

Thank you.

**Comment by rolfl** [comment] 2017-10-06 19:57
If there's no whitespace on any of the input XML content, then I would expect the output to be all on one line (after the xml declaration). the `Text.PRESERVE` will use the same whitespace in the input, in the output. Can you give an example of what your input process is for building the JDOM document that you believe is outputting wrong?

**Comment by Vanilla5113** [comment] 2017-10-06 20:13
It seems to me that this issue is not actually related to whitespace in the text nodes within each element (which are what the text modes are concerned with if I understand correctly), but rather the indent and line separators of the format (between elements).

The input XML does contain new lines and indents, but regardless of this, shouldn't the outputter use the indent and line separators specified by the Format and FormatStack? Again, it seems to me that text mode PRESERVE refers to the text value within the element (between the tags only, not outside the tags).

**Comment by rolfl** [comment] 2017-10-06 20:33
Hmm, taking a few steps back, you're right that there is a problem in interpretation here.... the setTextMode is overriding some settings you've already set.... so, it will work if you change:

```
Format format = Format.getRawFormat();
format.setIndent("\t");
format.setLineSeparator("\r\n");
format.setTextMode(Format.TextMode.PRESERVE);
```

to be:

```
Format format = Format.getRawFormat();
format.setIndent("\t");
format.setLineSeparator("\r\n");
```

(changing the indent/separator after TextMode - since the PRESERVE text mode is the default for RawFormat).

**Comment by Vanilla5113** [comment] 2017-10-06 22:10
No, that does not fix the issue. Please re-read my original post. It wouldn’t even fix it if I could change those properties in the FormatStack object, because the default XMLOutputProcessor doesn’t use those properties when writing elements.
AbstractXMLOutputProcessor:861
```
// we have some content.
write(out, ">");
if (!walker.isAllText()) {
                // we need to newline/indent
                textRaw(out, fstack.getPadBetween());
}

printContent(out, fstack, nstack, walker);

if (!walker.isAllText()) {
                // we need to newline/indent
                textRaw(out, fstack.getPadLast());
}
write(out, "</");
write(out, element.getQualifiedName());
write(out, ">");
```
As you can see above, it uses these method calls on the FormatStack object:
```
public String getPadBetween() {
                return levelEOLIndent[depth];
}
public String getPadLast() {
                return termEOLIndent[depth];
}
```
But these always return null (resulting in nothing being written) because of this:
FormatStack:177 (constructor)
```
if (mode[depth] == TextMode.PRESERVE) {
                // undo any special indenting and end-of-line management:
                levelIndent[depth] = null;
                levelEOL[depth] = null;
                levelEOLIndent[depth] = null;
                termEOLIndent[depth] = null;
}
```
… and this…
FormatStack:449 (push() method)
```
if (levelIndent[prev] == null || levelEOL[prev] == null) {
                levelIndent[depth] = null;
                levelEOL[depth] = null;
                levelEOLIndent[depth] = null;
                termEOLIndent[depth] = null;
}
```

I highly recommend that you review this. There IS a problem in the code.

**Comment by Vanilla5113** [comment] 2017-10-06 22:12
No, that does not fix the issue. Please re-read my original post. It wouldn’t even fix it if I could change those properties in the FormatStack object, because the default XMLOutputProcessor doesn’t use those properties when writing elements.
AbstractXMLOutputProcessor:861
```
// we have some content.
write(out, ">");
if (!walker.isAllText()) {
	// we need to newline/indent
	textRaw(out, fstack.getPadBetween());
}

printContent(out, fstack, nstack, walker);

if (!walker.isAllText()) {
	// we need to newline/indent
	textRaw(out, fstack.getPadLast());
}
write(out, "</");
write(out, element.getQualifiedName());
write(out, ">");
```
As you can see above, it uses these method calls on the FormatStack object:
```
public String getPadBetween() {
	return levelEOLIndent[depth];
}
public String getPadLast() {
	return termEOLIndent[depth];
}
```
But these always return null (resulting in nothing being written) because of this:
FormatStack:177 (constructor)
```
if (mode[depth] == TextMode.PRESERVE) {
	// undo any special indenting and end-of-line management:
	levelIndent[depth] = null;
	levelEOL[depth] = null;
	levelEOLIndent[depth] = null;
	termEOLIndent[depth] = null;
}
```
… and this…
FormatStack:449 (push() method)
```
if (levelIndent[prev] == null || levelEOL[prev] == null) {
	levelIndent[depth] = null;
	levelEOL[depth] = null;
	levelEOLIndent[depth] = null;
	termEOLIndent[depth] = null;
}
```

I highly recommend that you review this. There IS a problem in the code.

**Comment by Vanilla5113** [comment] 2017-10-06 23:17
Just realized my interpretation of the code is incorrect, because in this segment:
```
// we have some content.
write(out, ">");
if (!walker.isAllText()) {
	// we need to newline/indent
	textRaw(out, fstack.getPadBetween());
}

printContent(out, fstack, nstack, walker);

if (!walker.isAllText()) {
	// we need to newline/indent
	textRaw(out, fstack.getPadLast());
}
write(out, "</");
write(out, element.getQualifiedName());
write(out, ">");
```
the calls to `textRaw()` under the condition `!walker.isAllText()` are, in fact, happening before and after the text inside the element, rather than in between elements.

But it still didn't work to simply not set the text mode in the Format object. I'm going to do some additional debugging to find the answer.

**Comment by Vanilla5113** [comment] 2017-10-09 16:57
I haven't figured this out yet, but I haven't had much time. Have you looked into this?

**Comment by rolfl** [comment] 2017-10-09 17:21
Heh, Canadian Thanksgiving weekend, I'm out of town. Back online with my dev machine tomorrow.

**Comment by Vanilla5113** [comment] 2017-10-09 17:28
Sorry, had no idea it was Canadian Thanksgiving weekend. Enjoy.

**Comment by rolfl** [comment] 2017-10-15 15:40
Circling back to this, is there an example input XML file you have, or can share, and the expected output? I am playing with some documents but to my mind it's doing the "right thing" so I have not successfully reproduced this issue.

**Comment by rolfl** [comment] 2017-10-15 16:09
OK, running through this issue from the top again, there's a few things to cover.

First up, the JDOM 1.x handling of PRESERVE was broken, so trying to reproduce it with JDOM 2.x is a mistake. Note that PRESERVE is intended to handle situations where the XML content may look like:

```
<root>
   <emt xml:space="preserve">

        keep this white space formatted like this

   </emt>
</root>
```

Note that XML handlers should not modify any whitespace in the `emt` element. JDOM 1.x would do that if the formatter was set at a higher level even though the XML element itself would require an override for the formatter at a specific element (and it's subtree).

Having said that JDOM 1.x was mishandling the preserve, it's apparent that the handling in JDOM 2.x is not exactly intuitive either.... but, your intended solution of preserving all text is immediately forcing the outputter in to the raw mode where any indents/paddings are ignored.

What you really want to do is set the formatter in to an innocuous mode (not preserve), and to override the indents/padding/newlines with something useful.

Consider using something like:

```
    public static void main(String[] args) throws IOException {
        Element low1 = new Element("low1").setText("compact");
        Element mid1 = new Element("mid1").addContent(low1);
        Element low2 = new Element("low2").addContent("low2");
        Element mid2 = new Element("mid2").addContent("  padded  ").addContent(low2);
        Element mid3 = new Element("mid3").addContent("    ");
        Element root = new Element("root").addContent(mid1).addContent(mid2).addContent(mid3);
        
        Document doc = new Document(root);
        
        Format format = Format.getRawFormat();
        format.setTextMode(Format.TextMode.TRIM_FULL_WHITE);
        format.setIndent("\t");
        format.setLineSeparator("\r\n");

        String strResponse = new XMLOutputter(format).outputString(doc);
        System.out.println(strResponse);
    }

```
which will output:

```
<?xml version="1.0" encoding="UTF-8"?>
<root>
	<mid1>
		<low1>compact</low1>
	</mid1>
	<mid2>
		  padded  
		<low2>low2</low2>
	</mid2>
	<mid3 />
</root>

```

(note that `mid3` is completely whitespace so it is "contracted" to `<mid3 />`.

**Comment by rolfl** [comment] 2021-07-02 02:06
Closing due to being an issue in 1.1 handling of whitespace, that's working in 2.x. The migration from one to the other causes issues, but they are actually fixed now. Handling whitespace in 2.x requires different settings than 1.x

**Closed by rolfl** 2021-07-02 02:06 UTC
