### ISSUE TITLE
Problem with a Mediawiki-API

### ISSUE THREAD

**Issue by dabpunkt** [hunterhacker/jdom#144] opened 2015-03-01 21:19 UTC
Hello,
I use jdom to access the Mediawiki-API of several Wikipedias. Since some time, when I try to access the API of the Russian-Wikipedia, I get a strange “Premature end of file.”-error. AFAIS the XML is correct and there is really no difference between the Russian and the English output.
The following test-code shows the problem:

```java
public static void main(String[] args)
	{
		String url=
				"http://ru.wikipedia.org/"
				+ "w/api.php"
				+ "?action=query"
				+ "&titles=File:Inntalgewoelbe_seismik.gif"
				+ "&prop=info"
				+ "&continue="
				+ "&format=xml";
		
		URL apiURL;
		try
		{
			apiURL = new URL(url);
		} catch (MalformedURLException e)
		{
			throw new RuntimeException("Invalid api-URL", e);
		}
		
		URLConnection hc;
		try
		{
			hc = apiURL.openConnection();
		} catch (IOException e)
		{
			throw new RuntimeException("Could not get data from API", e);
		}
		hc.setRequestProperty("User-Agent", "JDOMTest");
		
		InputStream stream = null;
		try
		{
			stream = hc.getInputStream();
			
			Document doc = new SAXBuilder().build(stream);
			
		} catch (IOException e)
		{
			throw new RuntimeException(e);
		} catch (JDOMException e)
		{
			throw new RuntimeException(e);
			
		} finally {
			if (stream != null)
			{
				try
				{
					stream.close();
				} catch (IOException e)
				{
				}
			}
		}
		
	}
```
The code fails with ru.wikipedia, but works with en.wikipedia and even with jp.wikipedia (so non-ASCII seems not to be the problem). I use the last jdom 2.0.6-version.
If you need any other information, please ask. 

Sincerely,
DaB.

**Comment by rolfl** [comment] 2015-03-01 21:46
Hmm, there appears to be a change in the mediawiki default handling for HTTP connections now. When I  access your URL from the commandline using curl, I get:

```
curl -v 'http://ru.wikipedia.org/w/api.php?action=query&titles=File:Inntalgewoelbe_seismik.gif&prop=info&continue=&format=xml'
* Hostname was NOT found in DNS cache
*   Trying 208.80.154.224...
* Connected to ru.wikipedia.org (208.80.154.224) port 80 (#0)
> GET /w/api.php?action=query&titles=File:Inntalgewoelbe_seismik.gif&prop=info&continue=&format=xml HTTP/1.1
> User-Agent: curl/7.35.0
> Host: ru.wikipedia.org
> Accept: */*
> 
< HTTP/1.1 301 TLS Redirect
* Server Varnish is not blacklisted
< Server: Varnish
< Location: https://ru.wikipedia.org/w/api.php?action=query&titles=File:Inntalgewoelbe_seismik.gif&prop=info&continue=&format=xml
< Accept-Ranges: bytes
< Date: Sun, 01 Mar 2015 21:38:18 GMT
< X-Varnish: 2575807500
< Age: 0
< Via: 1.1 varnish
< Connection: close
< X-Cache: cp1052 frontend miss (0)
< Set-Cookie: GeoIP=CA:Toronto:43.6440:-79.4062:v4; Path=/; Domain=.wikipedia.org
< 
* Closing connection 0
```

That shows that the site is redirecting you to the HTTPS version, and immediately closing the connection (no data supplied, hence the premature end of stream).

Sure enough, when I change your code to access the site using HTTPS instead of HTTP, it works fine,

In theory, you should be able to set HttpURLConnections to follow redirects system wide, using: http://docs.oracle.com/javase/8/docs/api/java/net/HttpURLConnection.html#setFollowRedirects-boolean-

but, that did not work for me.....

**Closed by rolfl** 2015-03-01 21:46 UTC

**Comment by rolfl** [comment] 2015-03-01 22:03
As a followup - there is a specific and deliberate decision made in Java to not follow redirects between protocols: http://bugs.java.com/view_bug.do?bug_id=4620571

Essentially, it will not go from HTTP to HTTPS (or back). An application-side process for handling this is required... apparently "by design".

**Comment by dabpunkt** [comment] 2015-03-01 22:57
ok, the redirect is the problem, I changed it to https. Thanks for looking :-).
